### ISSUE TITLE
Support for C++ 11

### ISSUE THREAD

**Issue by paulocoutinhox** [Dugy/quick_arg_parser#2]
Hi,

Can you add support for C++ 11?

Thanks and great library.

**Comment by Dugy** [comment]
If I won't manage to figure out how to get it to support `std::optional` (C++17), I will do it, the idea should be possible to get working with C++11.

**Comment by paulocoutinhox** [comment]
Hi,

Maybe you can get something form here:
https://github.com/TartanLlama/optional
and
https://github.com/martinmoene/optional-lite

Thanks.

**Comment by Dugy** [comment]
On Reddit, there was a discussion that a custom imitation of `std::optional` would help solve the issue. If I resorted to adding a custom `std::optional`, it would probably be one with slightly modified behaviour that would work with this. Implementing it isn't hard as long as you know about placement new.

**Comment by Dugy** [comment]
Done in commit 1075dd2.
