### ISSUE TITLE
Not Posix compliant, nor Gnu getopt_long compliant

### ISSUE THREAD

**Issue by MtnViewJohn** [Dugy/quick_arg_parser#3]
Here is some test code derived from your short example:
[test.cpp.zip](https://github.com/Dugy/quick_arg_parser/files/5909058/test.cpp.zip)

Here is its output:
% ./a.out . --efficiency 9 -v
Folder .
Efficiency 9

% ./a.out . -e 9 -v
Folder .
Efficiency 9

These should also work according to the Posix getopt() spec, but they don't.
% ./a.out . -e9 -v
Switch group -e9 contains a switch that needs an argument

% ./a.out . -ve 9
Switch group -ve contains a switch that needs an argument

% ./a.out . -ve9
Switch group -ve9 contains a switch that needs an argument

This should work, but it doesn't:
% ./a.out . --efficiency=9 -v
Unknown switch --efficiency=9

**Comment by Dugy** [comment]
I originally didn't intend to support many ways of writing the options, as the `-e9` and `-e=9` variants were rarely used and had little benefit. However, I also didn't expect this to be used to refactor old programs. So I have added support for those.
